modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory (32 is current forge version)

# License
license="GNU GPLv3"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/gottsch/gottsch-minecraft-dungeonblocks/issues" #optional

credits="gottsch" #optional

[[mods]] #mandatory
modId="dungeonblocks" #mandatory
version="1.1.0" #mandatory
displayName="Dungeon Blocks" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://raw.githubusercontent.com/gottsch/gottsch-minecraft-dungeonblocks/1.16.5-master/DungeonBlocks/update.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/dungeonblocks" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="dungeonblocks_logo.png" #optional
description='''
gottsch's DungeonBlocks
'''

[[dependencies.examplemod]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[39,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="gottschcore"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.1,1.19)"
    ordering="BEFORE"
    side="BOTH"