modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory. 26 for 1.14.2, 27 for 1.14.3

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/gottsch/gottsch-minecraft-dungeonblocks/issues" #optional

credits="gottsch" #optional

[[mods]] #mandatory
modId="dungeonblocks" #mandatory
version="1.0.0" #mandatory
displayName="Dungeon Blocks" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://raw.githubusercontent.com/gottsch/gottsch-minecraft-dungeonblocks/master/DungeonBlocks/update.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/dungeonblocks" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="dungeonblocks_logo.png" #optional
description='''
gottsch's DungeonBlocks
'''
      [[dependencies.dungeonblocks]]
        modId="forge"
        mandatory=true
        versionRange="[28,)"
        ordering="NONE"
        side="BOTH"

      [[dependencies.dungeonblocks]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.14.4]"
        ordering="NONE"
        side="BOTH"
        
      [[dependencies.dungeonblocks]]
        modId="gottschcore"
        mandatory=true
        versionRange="[1,)"
        ordering="NONE"
        side="BOTH"