modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory. 26 for 1.14.2, 27 for 1.14.3
credits="Thanks gottsch for this example!" #optional
[[mods]] #mandatory
modId="dungeonblocks" #mandatory
version="1.0" #mandatory
displayName="Dungeon Blocks" #mandatory
description='''
gottsch's DungeonBlocks
'''